### ISSUE TITLE
Crash in 1.12.2 No other mods

### ISSUE THREAD

**Issue by ghost** [SmithsModding/SmithsCore#15]
I tested this with no other mods and this was the output:
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
[13:09:41] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:09:41] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:09:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[13:09:41] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2729 for Minecraft 1.12.2 loading
[13:09:41] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_171, running on Mac OS X:x86_64:10.13.5, installed at /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
[13:09:41] [main/INFO] [FML]: Searching /Users/charles/Documents/Curse/Minecraft/Instances/Test/mods for mods
[13:09:41] [main/INFO] [FML]: Loading tweaker com.smithsmodding.shading.mixin.launch.MixinTweaker from smithscore-1.12.2-1.4.0-8621-SNAPSHOT.jar
[13:09:41] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:09:41] [main/INFO] [LaunchWrapper]: Loading tweak class name com.smithsmodding.shading.mixin.launch.MixinTweaker
Exception in thread "main" [13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: com.smithsmodding.shading.mixin.service.ServiceNotAvailableError: No mixin host service is available
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.smithsmodding.shading.mixin.service.MixinService.getServiceInstance(MixinService.java:113)
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.smithsmodding.shading.mixin.service.MixinService.getService(MixinService.java:106)
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.smithsmodding.shading.mixin.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:77)
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.smithsmodding.shading.mixin.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[13:09:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Is there a specific Forge version or support mod that should be used?

**Comment by ghost** [comment]
I probably should have mentioned SC 1.4.0-8621-SNAPSHOT (the most recent beta as of posting)

**Comment by marchermans** [comment]
I think that is a bug on My side.
I will have to repackage that XD. I am busy with Bachelors and stuff in RL. Hopefully i can get it repackaged tonight though.....

**Comment by marchermans** [comment]
Also we have a new repo under LDTeam/SmithsGaming.....
Which reminds me i need todo some general cleanup.

**Comment by Iashar** [comment]
Just got a crash with this as well, should I remove for now?

**Comment by marchermans** [comment]
I am currently in ill health. Please remove for now. I will update as soon as I possibly can.

**Comment by ghost** [comment]
I've got a bit of that myself right now. Rest, take care of yourself. These issues are a complement on your ideas and a desire to contribute through testing, not an injunction to stress. We appreciate all you've done and want you to recover for your own happiness. We look forward to your return whenever that is. Thank you.

**Comment by marchermans** [comment]
Thanks I have the code. Just not published.......

**Comment by marchermans** [comment]
Thanks I have the code. Just not published.......

**Comment by marchermans** [comment]
@scribbler957 I fixed it now, Both armory and SmithsCore are now live and runnable

**Comment by ghost** [comment]
Great, thanks. I'll add them back for my next game. :)

**Comment by marchermans** [comment]
I am working on the TCon integration now
Should be done in the next couple of days.
